$(var namespace)/mmpf:
  ros__parameters:
    map_topic: /$(var namespace)/map
    costmap_topic: /$(var namespace)/global_costmap/costmap
    robot_base_frame: base_footprint                            # Without namespace (prefix)
    robot_frame_prefix: robot                                   # robot is the prefix where frames are s.t. robot1/base_footprint, robot2/base_footprint
    rate: 1.0
    robot_count: 1
    inflation_radius: 6.0


